In [ ]:
import os
os.chdir('???')
os.getcwd()

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline

In [3]:
df = pd.read_csv("data/challenger.csv")
df.head()

Temp Failure  Failure1
0    53       Y         1
1    57       Y         1
2    58       Y         1
3    63       Y         1
4    66       N         0

## StatModels

In [4]:
df.columns

Index(['Temp', 'Failure', 'Failure1'], dtype='object')

In [5]:
import statsmodels.api as sm
X = df[['Temp']]
X = sm.add_constant(X, prepend=False)
X.head()

Temp  const
0    53    1.0
1    57    1.0
2    58    1.0
3    63    1.0
4    66    1.0

In [6]:
y = df['Failure1']

In [7]:
import statsmodels.discrete.discrete_model as sd
model = sd.Logit(y, X)
result = model.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.441635
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Failure1   No. Observations:                   23
Model:                          Logit   Df Residuals:                       21
Method:                           MLE   Df Model:                            1
Date:                Thu, 05 Mar 2020   Pseudo R-squ.:                  0.2813
Time:                        09:37:37   Log-Likelihood:                -10.158
converged:                       True   LL-Null:                       -14.134
Covariance Type:            nonrobust   LLR p-value:                  0.004804
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Temp          -0.2322      0.108     -2.145      0.032      -0.444      -0.020
const         15.0429      7.379      2.039      0.041       0.581      29.505
==============================================================================
"""

In [8]:
result.params

Temp     -0.232163
const    15.042902
dtype: float64

## Scikitlearn

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [23]:
# lecture example uses all data to train (test_size=0.0).
# typically, test_size is set to be 0.30

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.0, random_state=99)

ValueError: test_size=0.0 should be either positive and smaller than the number of samples 23 or a float in the (0, 1) range

In [14]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
model.coef_

array([[-1.99374319e-01,  7.15773318e-06]])

In [16]:
model.intercept_

array([12.79534789])

In [17]:
# lecture example uses all data to train
# typically use X_test to do prediction

predictions = model.predict(X_train)
predictions

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [18]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix 

print(confusion_matrix(y_train,predictions))

[[11  0]
 [ 2  3]]


In [19]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix 

print(classification_report(y_train, predictions))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92        11
           1       1.00      0.60      0.75         5

    accuracy                           0.88        16
   macro avg       0.92      0.80      0.83        16
weighted avg       0.89      0.88      0.86        16



In [20]:
df2 = pd.read_csv("data/heart.csv")
df2.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1